export const ADVANTAGES_CATALOG = [
  { id: 'aceleracao', name: 'Aceleração', cost: '1pt', desc: 'Você se move muito rápido, com movimentos extras e ganho em perseguição.' },
  { id: 'mais_acao', name: '+Ação', cost: '1pt cada', desc: 'Fornece +2 Pontos de Ação além dos de seu Poder.' },
  { id: 'acumulador', name: 'Acumulador', cost: '1pt', desc: 'Quanto mais seus ataques acertam, mais forte você bate ou argumenta.' },
  { id: 'agil', name: 'Ágil', cost: '1pt', desc: 'Recebe H+2 em testes envolvendo agilidade, coordenação ou equilíbrio.' },
  { id: 'ajudante', name: 'Ajudante', cost: '1pt cada', desc: 'Você tem algo ou alguém com quem pode contar em diversas situações.' },
  { id: 'alcance', name: 'Alcance', cost: '1–2pt', desc: 'Seus ataques acertam mais longe sem penalidades.' },
  { id: 'anulacao', name: 'Anulação', cost: '2pt', desc: 'Você consegue impedir o alvo de usar um de seus poderes.' },
  { id: 'arena', name: 'Arena', cost: '1pt cada', desc: 'Você tem Ganho em testes em um certo tipo de terreno.' },
  { id: 'artefato', name: 'Artefato', cost: '1pt ou mais', desc: 'Você possui um item especial único com benefícios de jogo.' },
  { id: 'ataque_especial', name: 'Ataque Especial', cost: '1pt cada', desc: 'Técnica superior ou arma que causa efeitos específicos ao atacar.' },
  { id: 'base', name: 'Base', cost: '1pt', desc: 'Uma base de operações para qual pode viajar fora de combate e descansar.' },
  { id: 'brutal', name: 'Brutal', cost: '1pt cada', desc: 'Você recupera energias causando dano e derrotando inimigos.' },
  { id: 'carismatico', name: 'Carismático', cost: '1pt', desc: 'Recebe P+2 em interações sociais ou fazerem que gostem de você.' },
  { id: 'clone', name: 'Clone', cost: '1pt', desc: 'Pode criar cópias exatas que anulam ataques recebidos.' },
  { id: 'confusao', name: 'Confusão', cost: '1pt', desc: 'Deixa o oponente tonto, incapaz de escolher alvos para habilidades.' },
  { id: 'cura', name: 'Cura', cost: '1pt', desc: 'Cura PV e possibilita repetição de testes de resistência seus e de aliados.' },
  { id: 'defesa_especial', name: 'Defesa Especial', cost: '1pt cada', desc: 'Técnica de defesa superior para proteger você ou aliados.' },
  { id: 'desgaste', name: 'Desgaste', cost: '1pt', desc: 'O alvo sofre o mesmo dano do seu ataque outra vez na rodada seguinte.' },
  { id: 'devoto', name: 'Devoto', cost: '1pt', desc: 'Você tem Ganho ao defender uma causa, crença ou filosofia.' },
  { id: 'elo_mental', name: 'Elo Mental', cost: '1pt', desc: 'Ligação telepática e compartilhamento de recursos com um aliado.' },
  { id: 'estender', name: 'Estender', cost: '1pt', desc: 'Estenda efeitos de vantagens pessoais para aliados próximos.' },
  { id: 'famoso', name: 'Famoso', cost: '1pt', desc: 'Recebe Ganho em testes sociais com NPCs que o conheçam.' },
  { id: 'foco', name: 'Foco', cost: '1pt', desc: 'Concentra-se para obter um acerto crítico automático no turno seguinte.' },
  { id: 'forte', name: 'Forte', cost: '1pt', desc: 'Recebe P+2 em testes para empreender esforço físico.' },
  { id: 'genio', name: 'Gênio', cost: '1pt', desc: 'Recebe H+2 para problemas com inteligência, raciocínio e conhecimento.' },
  { id: 'golpe_final', name: 'Golpe Final', cost: '1pt', desc: 'Ataque de escala elevada contra alvo que esteja perto da derrota.' },
  { id: 'grimorio', name: 'Grimório', cost: '1pt ou mais', desc: 'Fonte de conhecimentos para começar com truques ou técnicas.' },
  { id: 'ilusao', name: 'Ilusão', cost: '2pt', desc: 'Você consegue criar ilusões visuais que enganam os sentidos.' },
  { id: 'imitar', name: 'Imitar', cost: '1pt', desc: 'Você consegue imitar uma das vantagens usadas pelo seu alvo.' },
  { id: 'imortal', name: 'Imortal', cost: '1pt', desc: 'Em testes de morte, não sofre resultados piores que Inconsciente.' },
  { id: 'improviso', name: 'Improviso', cost: '2pt', desc: 'Aprende uma perícia provisória até o final da cena na hora do aperto.' },
  { id: 'imune', name: 'Imune', cost: '1pt cada', desc: 'Imunidade contra necessidades naturais, doenças, fadiga mental ou afins.' },
  { id: 'incorporeo', name: 'Incorpóreo', cost: '2pt', desc: 'Você se torna intangível, imune a danos físicos.' },
  { id: 'inimigo', name: 'Inimigo', cost: '1–2pt cada', desc: 'Acertos críticos fáceis e Ganhos ao enfrentar um tipo específico de criatura.' },
  { id: 'inofensivo', name: 'Inofensivo', cost: '1pt', desc: 'Aparência não ameaçadora confere vantagem em iniciativas e surpresas.' },
  { id: 'instrutor', name: 'Instrutor', cost: '1pt', desc: 'Você ensina ou inspira aliados, concedendo os benefícios de uma perícia sua.' },
  { id: 'inventario', name: 'Inventário', cost: '1–3pt', desc: 'Carrega mais itens consumíveis extras com base no nível da vantagem.' },
  { id: 'invisivel', name: 'Invisível', cost: '1–2pt', desc: 'Torna-se invisível, ganhando vantagens furtivas e forçando Perda aos atacantes.' },
  { id: 'irresistivel', name: 'Irresistível', cost: '1pt', desc: 'Seus poderes são mais difíceis de sofrer resistência ou anulação pelos alvos.' },
  { id: 'maestria', name: 'Maestria', cost: '1pt cada', desc: 'Acertos críticos mais fáceis para rolagens de uma perícia específica.' },
  { id: 'magia', name: 'Magia', cost: '2pt', desc: 'Manipula forças sobrenaturais e aplica bônus mágicos em testes.' },
  { id: 'mais_mana', name: '+Mana', cost: '1pt cada', desc: 'Fornece +10 Pontos de Mana além dos de sua Habilidade.' },
  { id: 'mais_membros', name: '+Membros', cost: '2pt', desc: 'Membros extras permitem realizar uma segunda ação não combativa por turno.' },
  { id: 'mentor', name: 'Mentor', cost: '1pt cada', desc: 'Benefícios providos pelos antigos ensinamentos de uma perícia específica.' },
  { id: 'obstinado', name: 'Obstinado', cost: '1pt', desc: 'Gaste um ponto de P, H ou R temporariamente no lugar de um Ponto de Ação.' },
  { id: 'paralisia', name: 'Paralisia', cost: '1pt', desc: 'Consegue prender um alvo e deixá-lo imobilizado em vez de causar dano.' },
  { id: 'patrono', name: 'Patrono', cost: '1pt', desc: 'Recebe Ganho em compras e itens consumíveis extras a serviço da instituição.' },
  { id: 'punicao', name: 'Punição', cost: '1–2pt', desc: 'Impõe a um alvo uma desvantagem por ataque em vez de dano.' },
  { id: 'regeneracao', name: 'Regeneração', cost: '1–2pt', desc: 'Recupera PV a cada turno sem consumir ações ou recursos extras.' },
  { id: 'resoluto', name: 'Resoluto', cost: '1pt', desc: 'Recebe R+2 em testes envolvendo força de vontade e resolução mental.' },
  { id: 'riqueza', name: 'Riqueza', cost: '2, 4 ou 6pt', desc: 'Aumenta as escalas e testes de compras utilizando sua vasta riqueza.' },
  { id: 'sentido', name: 'Sentido', cost: '1pt cada', desc: 'Pode enxergar coisas impossíveis, como infravisão, radar, raio x, entre outros.' },
  { id: 'telepata', name: 'Telepata', cost: '1pt', desc: 'Lê pensamentos para interações sociais e antecipar defesa contra oponentes.' },
  { id: 'teleporte', name: 'Teleporte', cost: '1pt', desc: 'Desloca-se sem ser impedido por terrenos difíceis com grande facilidade.' },
  { id: 'torcida', name: 'Torcida', cost: '1pt', desc: 'Recebe benefício motivacional sempre que acompanhado ou ovacionado.' },
  { id: 'transformacao', name: 'Transformação', cost: '1-2pt cada', desc: 'Assume uma forma diferente com perícias e vantagens totalmente distintas.' },
  { id: 'mais_vida', name: '+Vida', cost: '1pt cada', desc: 'Fornece +10 Pontos de Vida além dos de sua Resistência.' },
  { id: 'vigoroso', name: 'Vigoroso', cost: '1pt', desc: 'Recebe R+2 em testes envolvendo fadiga, venenos, doenças e mortes.' },
  { id: 'voo', name: 'Voo', cost: '1pt', desc: 'Capacidade natural de voo e imunidade contra restrições de alguns terrenos.' }
];

export const DISADVANTAGES_CATALOG = [
  { id: 'ambiente', name: 'Ambiente', cost: '-1pt', desc: 'Dependência climática causando Perda caso retirado de seu habitat.' },
  { id: 'amnesia', name: 'Amnésia', cost: '-2pt', desc: 'O personagem não lembra de suas vantagens, perícias ou do próprio passado.' },
  { id: 'antipatico', name: 'Antipático', cost: '-1pt', desc: 'Testes de Poder em interações sociais têm Perda e falham em ser críticos.' },
  { id: 'assombrado', name: 'Assombrado', cost: '-1pt ou -2pt', desc: 'Assombração, sentimento ruim ou memória que causa perda de concentração no combate.' },
  { id: 'atrapalhado', name: 'Atrapalhado', cost: '-1pt', desc: 'Testes de Habilidade envolvendo coordenação falham criticamente e geram Perda.' },
  { id: 'aura', name: 'Aura', cost: '-1pt ou -2pt', desc: 'Aura pesada que prejudica os testes de aliados ou alvos em seu raio de alcance.' },
  { id: 'bateria', name: 'Bateria', cost: '-1pt', desc: 'Fica indefeso sem PM, e sofre penalidades assim que sua energia fica baixa.' },
  { id: 'codigo', name: 'Código', cost: '-1pt cada', desc: 'Código de conduta restrito cuja violação acarreta em penalidades por culpa.' },
  { id: 'dependencia', name: 'Dependência', cost: '-2pt', desc: 'Necessita de fonte ilícita para funcionar bem e gera Perda caso não suprida.' },
  { id: 'diferente', name: 'Diferente', cost: '-1pt', desc: 'Corpo exótico que exige aparatos sob medida e dificulta itens convencionais.' },
  { id: 'elo_vital', name: 'Elo Vital', cost: '-1pt', desc: 'Os danos sofridos por você recaem em igual magnitude em um de seus aliados.' },
  { id: 'fracote', name: 'Fracote', cost: '-1pt', desc: 'Testes de esforço físico contam com Perdas e são desprovidos de crítico.' },
  { id: 'fragil', name: 'Frágil', cost: '-1pt', desc: 'Tem Perda ao testar resistências a danos letais, fadigantes e afins.' },
  { id: 'fraqueza', name: 'Fraqueza', cost: '-1pt ou -2pt', desc: 'Condição, objeto ou tipo elementar específico deixam o personagem com Perda.' },
  { id: 'furia', name: 'Fúria', cost: '-2pt', desc: 'Frenesi incontrolável durante combates; foca um alvo gastando dobro de PM.' },
  { id: 'inapto', name: 'Inapto', cost: '-1pt', desc: 'Testes com uma perícia específica nunca dão certo e causam falhas críticas.' },
  { id: 'inculto', name: 'Inculto', cost: '-1pt', desc: 'Desconhece língua e hábitos da região, impossibilitando testes socioculturais limpos.' },
  { id: 'indeciso', name: 'Indeciso', cost: '-1pt', desc: 'Em testes envolvendo força de vontade, há Perda sem possibilidade de críticos.' },
  { id: 'infame', name: 'Infame', cost: '-1pt', desc: 'As pessoas te conhecem por péssimos motivos; seus testes sociais contam com Perda.' },
  { id: 'lento', name: 'Lento', cost: '-1pt', desc: 'Desloca-se de forma limitada e sempre sofre com iniciativas ruins e penalizadas.' },
  { id: 'maldicao', name: 'Maldição', cost: '-1pt ou -2pt', desc: 'Um azar cósmico, fardo ou evento danoso persistente e muito problemático.' },
  { id: 'monstruoso', name: 'Monstruoso', cost: '-1pt', desc: 'Feições pavorosas que perdem testes sociais facilmente e quebram sigilo passivo.' },
  { id: 'municao', name: 'Munição', cost: '-1pt', desc: 'Exige recarga, que gasta uma ação extra antes de o ataque principal sair sem penalidades.' },
  { id: 'pacifista', name: 'Pacifista', cost: '-1pt ou -2pt', desc: 'Não pode ferir ninguém livremente ou atacar sob certas condições pacíficas.' },
  { id: 'pobreza', name: 'Pobreza', cost: '-1pt', desc: 'Todos e quaisquer testes de compra são marcados por profunda Perda de rolagem.' },
  { id: 'ponto_fraco', name: 'Ponto Fraco', cost: '-1pt', desc: 'Se um adversário notar seu tique de batalha, ele recebe Ganhos contra você.' },
  { id: 'protegido', name: 'Protegido', cost: '-1pt', desc: 'Sofre intensamente sempre que o aliado estiver ferido, capturado ou ameaçado.' },
  { id: 'restricao', name: 'Restrição', cost: '-1pt ou -2pt', desc: 'As vantagens gastam o dobro do PM regular frente às amarras impostas pela sua restrição.' },
  { id: 'sem_vida', name: 'Sem Vida', cost: '-2pt', desc: 'Como máquina ou defunto, os meios normais de cura deixam de te restabelecer.' },
  { id: 'tapado', name: 'Tapado', cost: '-1pt', desc: 'Raciocínio lento; as jogadas de conhecimento sofrem Perdas sem direito ao crítico.' },
  { id: 'transtorno', name: 'Transtorno', cost: '-1pt cada', desc: 'Sofre transtornos compulsivos como fobia e mitomania dificultando jogadas cruciais.' },
  { id: 'utensilio', name: 'Utensílio', cost: '-1pt ou -2pt', desc: 'A dependência de um instrumento para rodar perícias. Se perdido, tudo se inviabiliza.' }
];
