import type { CharacterArchetype } from '../../types/character';

export const ARCHETYPES_CATALOG: CharacterArchetype[] = [
  {
    id: 'none',
    name: 'Sem Arquétipo',
    cost: 0,
    group: 'Livre',
    desc: 'Personagem sem arquétipo específico.',
    traits: [],
  },
  {
    id: 'humano',
    name: 'Humano',
    cost: 0,
    group: 'Base',
    desc: 'O arquétipo humano é o padrão para personagens sem outro povo específico.',
    traits: ['Mais Além'],
    grantedEffects: [
      { id: 'arch_humano_mais_alem', name: 'Mais Além', desc: 'Gaste 2PM para ter Ganho em um teste.', attribute: 'any', bonusType: 'none', extraDice: 1, duration: 'instant', costValue: 2, costResource: 'PM' },
    ],
    notes: ['Uma vez por cena, pode gastar 2PM para ter Ganho em um teste.'],
  },
  {
    id: 'aberrante',
    name: 'Aberrante',
    cost: 1,
    group: 'Base',
    desc: 'Ser bizarro, mutante ou extraplanar demais para o mundo natural.',
    traits: ['Deformidade', 'Teratismo'],
    grantedDisadvantages: ['monstruoso'],
    notes: ['Escolha uma perícia para receber atributo +1 ao testá-la.', 'Recebe uma Técnica Comum à escolha, respeitando exigências.'],
  },
  {
    id: 'abissal',
    name: 'Abissal',
    cost: 1,
    group: 'Base',
    desc: 'Ser infernal ou vindo de planos malignos.',
    traits: ['Desfavor'],
    grantedAdvantages: ['agil'],
    grantedDisadvantages: ['infame'],
    grantedEffects: [
      { id: 'arch_abissal_desfavor', name: 'Desfavor', desc: 'Gaste 3PM para impor Perda ao alvo até o próximo turno.', attribute: 'poder', bonusType: 'none', extraDice: -1, duration: 'instant', costValue: 3, costResource: 'PM' },
    ],
  },
  {
    id: 'alien',
    name: 'Alien',
    cost: 1,
    group: 'Base',
    desc: 'Estrangeiro de outro planeta, tempo ou dimensão.',
    traits: ['Talento', 'Xenobiologia'],
    grantedDisadvantages: ['inculto'],
    notes: ['Escolha uma entre Ágil, Carismático, Forte, Gênio, Resoluto ou Vigoroso.', 'Escolha uma vantagem que possua para usar pela metade do custo em PM.'],
  },
  {
    id: 'anao',
    name: 'Anão',
    cost: 1,
    group: 'Base',
    desc: 'Povo robusto, teimoso e tradicional.',
    traits: ['Abascanto', 'A Ferro e Fogo'],
    grantedDisadvantages: ['lento'],
    notes: ['Recebe Sentido (Infravisão).', 'Em testes de Máquinas, o atributo correspondente tem +1.'],
  },
  {
    id: 'anfibio',
    name: 'Anfíbio',
    cost: 1,
    group: 'Base',
    desc: 'Ser aquático adaptado à vida dentro e fora d’água.',
    traits: ['Imune (Anfíbio)'],
    grantedAdvantages: ['vigoroso'],
    grantedDisadvantages: ['ambiente'],
  },
  {
    id: 'celestial',
    name: 'Celestial',
    cost: 1,
    group: 'Base',
    desc: 'Ser de planos superiores, anjo ou entidade benigna.',
    traits: ['Arrebatar'],
    grantedAdvantages: ['carismatico'],
    grantedDisadvantages: ['codigo::heroico'],
    grantedEffects: [
      { id: 'arch_celestial_arrebatar', name: 'Arrebatar', desc: 'Gaste 3PM para conceder Ganho no teste de um aliado.', attribute: 'any', bonusType: 'none', extraDice: 1, duration: 'instant', costValue: 3, costResource: 'PM' },
    ],
  },
  {
    id: 'centauro',
    name: 'Centauro',
    cost: 2,
    group: 'Base',
    desc: 'Criatura táurica de grande corpo e mobilidade.',
    traits: ['Corpo Táurico'],
    grantedAdvantages: ['vigoroso'],
    grantedDisadvantages: ['diferente'],
    grantedEffects: [
      { id: 'arch_centauro_corpo_taurico', name: 'Corpo Táurico', desc: 'Gaste 1PM para crítico 5+ em esforço físico, iniciativa, correr ou perseguir.', attribute: 'any', bonusType: 'none', critThresholdMod: -1, duration: 'instant', costValue: 1, costResource: 'PM' },
    ],
  },
  {
    id: 'ciborgue',
    name: 'Ciborgue',
    cost: 2,
    group: 'Base',
    desc: 'Ser vivo integrado a partes mecânicas ou artificiais.',
    traits: ['Construto Vivo'],
    grantedAdvantages: ['imune::resiliente'],
    notes: ['Também é imune a Abiótico e Doenças.', 'Escolha um Código ou Transtorno para Diretriz.'],
  },
  {
    id: 'construto',
    name: 'Construto',
    cost: 1,
    group: 'Base',
    desc: 'Ser artificial, mecânico ou mágico, feito e não nascido.',
    traits: [],
    grantedDisadvantages: ['bateria', 'sem_vida'],
    notes: ['Imune a Abiótico, Doenças, Resiliente e Sem Mente.'],
  },
  {
    id: 'dahllan',
    name: 'Dahllan',
    cost: 1,
    group: 'Base',
    desc: 'Povo de seiva vegetal, ligado à natureza e aos animais.',
    traits: ['Benção da Natureza', 'Empatia Selvagem'],
    grantedDisadvantages: ['codigo'],
    notes: ['Em testes de Animais, o atributo correspondente tem +1.', 'Código Dahllan: vegana e protetora de animais.'],
  },
  {
    id: 'elfo',
    name: 'Elfo',
    cost: 1,
    group: 'Base',
    desc: 'Povo elegante, longevo e místico.',
    traits: ['Impecável', 'Natureza Mística'],
    grantedDisadvantages: ['fragil'],
    notes: ['Escolha uma entre Ágil, Carismático ou Gênio.', 'Em testes de Mística, o atributo correspondente tem +1.'],
  },
  {
    id: 'fada',
    name: 'Fada',
    cost: 1,
    group: 'Base',
    desc: 'Ser feérico ligado à natureza e à magia.',
    traits: ['Magia das Fadas'],
    grantedDisadvantages: ['infame'],
    notes: ['Escolha entre Magia ou Ilusão com custo -1PM.', 'Escolha entre Diferente ou Frágil como delicadeza.'],
  },
  {
    id: 'fantasma',
    name: 'Fantasma',
    cost: 2,
    group: 'Base',
    desc: 'Morto-vivo imaterial e preso ao mundo.',
    traits: ['Espírito', 'Paralisia'],
    grantedAdvantages: ['devoto'],
    notes: ['Imune a Abiótico e Doenças.', 'Tem Sem Vida e condição incorpórea especial.'],
  },
  {
    id: 'goblin',
    name: 'Goblin',
    cost: 1,
    group: 'Base',
    desc: 'Pequeno, engenhoso e adaptável às cidades e ao caos.',
    traits: ['Espertalhão', 'Subterrâneo'],
    grantedDisadvantages: ['diferente'],
    notes: ['Recebe Sentido (Infravisão).'],
  },
  {
    id: 'hynne',
    name: 'Hynne',
    cost: 1,
    group: 'Base',
    desc: 'Pequenino hospitaleiro, rápido e surpreendentemente habilidoso.',
    traits: ['Atirador', 'Encantador'],
    grantedDisadvantages: ['diferente'],
  },
  {
    id: 'kallyanach',
    name: 'Kallyanach',
    cost: 2,
    group: 'Base',
    desc: 'Meio-dragão, poderoso e marcado por herança dracônica.',
    traits: ['Baforada'],
    grantedDisadvantages: ['codigo'],
    notes: ['Recebe Ataque Especial (Área, Distante ou Potente) com -1PM.', 'Escolha Forte ou Carismático.', 'Código dos Dragões.'],
  },
  {
    id: 'kemono',
    name: 'Kemono',
    cost: 1,
    group: 'Base',
    desc: 'Humanoide com traços animais ou animal antropomórfico.',
    traits: ['Percepção Apurada', 'Talento', 'Cacoete'],
    notes: ['Escolha uma entre Ágil, Carismático, Forte, Gênio, Resoluto ou Vigoroso.', 'Escolha uma entre Antipático, Atrapalhado, Fracote, Frágil, Indeciso ou Tapado.'],
  },
  {
    id: 'medusa',
    name: 'Medusa',
    cost: 1,
    group: 'Base',
    desc: 'Ser serpentiforme de grande apelo social e olhar perigoso.',
    traits: ['Olhar Atordoante'],
    grantedAdvantages: ['carismatico'],
    grantedDisadvantages: ['fracote'],
    grantedEffects: [
      { id: 'arch_medusa_olhar', name: 'Olhar Atordoante', desc: 'Gaste 3PM para atordoar um alvo Perto.', attribute: 'poder', bonusType: 'none', extraDice: -1, duration: 'instant', costValue: 3, costResource: 'PM' },
    ],
  },
  {
    id: 'minotauro',
    name: 'Minotauro',
    cost: 1,
    group: 'Base',
    desc: 'Humanoide bovino forte, competitivo e de instintos labirínticos.',
    traits: ['Atlético', 'Sentido Labiríntico'],
    grantedDisadvantages: ['transtorno::fobia'],
    notes: ['Fobia de altura.'],
  },
  {
    id: 'ogro',
    name: 'Ogro',
    cost: 1,
    group: 'Base',
    desc: 'Humanoide imenso, brutal e intimidador.',
    traits: ['Destruidor', 'Intimidador'],
    grantedDisadvantages: ['diferente'],
  },
  {
    id: 'osteon',
    name: 'Osteon',
    cost: 2,
    group: 'Base',
    desc: 'Morto-vivo esquelético consciente e persistente.',
    traits: ['Memória Póstuma'],
    grantedDisadvantages: ['sem_vida'],
    notes: ['Imune a Abiótico, Doenças e Resiliente.', 'Escolha uma perícia para atributo +1 ao testá-la.'],
  },
  {
    id: 'qareen',
    name: 'Qareen',
    cost: 2,
    group: 'Base',
    desc: 'Meio-gênio, criatura arcana prestativa e poderosa.',
    traits: ['Desejos'],
    grantedAdvantages: ['carismatico', 'magia'],
    grantedDisadvantages: ['codigo'],
    grantedEffects: [
      { id: 'arch_qareen_desejos', name: 'Desejos', desc: 'Magias para atender desejos têm custo reduzido.', attribute: 'any', bonusType: 'none', duration: 'scene', costValue: 0, costResource: 'none' },
    ],
    notes: ['Código da Gratidão.'],
  },
  {
    id: 'sauroide',
    name: 'Sauroide',
    cost: 2,
    group: 'Base',
    desc: 'Humanoide reptiliano robusto, furtivo e resistente.',
    traits: ['Camuflagem'],
    grantedAdvantages: ['resoluto', 'vigoroso'],
    grantedDisadvantages: ['fraqueza::grave'],
    notes: ['Fraqueza (Frio).'],
  },
  {
    id: 'vampiro',
    name: 'Vampiro',
    cost: 1,
    group: 'Base',
    desc: 'Ser noturno imortal, talentoso e amaldiçoado.',
    traits: [],
    grantedAdvantages: ['imortal'],
    notes: ['Escolha uma entre Ágil, Carismático, Forte, Gênio, Resoluto ou Vigoroso.', 'Fraqueza (luz do dia). Dependência não altera o custo total do arquétipo para PJ.'],
  },
];
