import type { RollBonus } from '../../types/character';

export const DRUID_WILD_SHAPE_OPTIONS = [
  { name: 'Aceleração', desc: 'Movimento extra por 1PM / Ganho em fugas' },
  { name: 'Ágil', desc: 'Ganho em iniciativa e testes de agilidade/acrobacia (+1D)' },
  { name: 'Alcance 1', desc: 'Ataques alcançam até Perto' },
  { name: 'Forte', desc: 'P+1 no atributo de Poder para esforço e dano' },
  { name: 'Imune (Anfíbio)', desc: 'Respira e age na água sem penalidades' },
  { name: 'Imune (Resiliente)', desc: 'Imunidade a venenos e doenças naturais' },
  { name: '+Membros', desc: 'Membros extras para ataques ou manobras' },
  { name: 'Paralisia', desc: 'Pode paralisar oponentes gastando PM' },
  { name: 'Regeneração', desc: 'Recupera PV a cada rodada ou descanso' },
  { name: 'Sentido Aguçado', desc: 'Ganho em testes de percepção (olfato/audição)' },
  { name: 'Sentido (Infravisão/Radar)', desc: 'Enxerga no escuro ou detecta por vibração' },
  { name: 'Vigoroso', desc: 'R+2 no atributo de Resistência' },
  { name: 'Voo', desc: 'Capaz de voar em velocidade normal' }
];

export const BONUS_PRESETS: Array<Omit<RollBonus, 'id'>> = [
  {
    name: 'Ataque Especial (Potente)',
    alias: '',
    attribute: 'poder',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
  },
  {
    name: 'Ataque Especial (Potente II)',
    alias: '',
    attribute: 'poder',
    bonusType: 'attr_mod',
    value: 4,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
  },
  {
    name: 'Ataque Especial (Perigoso)',
    alias: '',
    attribute: 'poder',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: -1,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
  },
  {
    name: 'Ataque Especial (Preciso)',
    alias: '',
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
  },
  {
    name: 'Ataque Especial (Choque)',
    alias: '',
    attribute: 'resistencia',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
  },
  {
    name: 'Ataque Especial (Titânico)',
    alias: '',
    attribute: 'poder',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: true,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
  },
  {
    name: 'Defesa Especial (Tenaz)',
    alias: '',
    attribute: 'resistencia',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
  },
  {
    name: 'Defesa Especial (Tenaz II)',
    alias: '',
    attribute: 'resistencia',
    bonusType: 'attr_mod',
    value: 4,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
  },
  {
    name: 'Defesa Especial (Blindada)',
    alias: '',
    attribute: 'resistencia',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: -1,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
  },
  {
    name: 'Defesa Especial (Esquiva)',
    alias: '',
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
  },
  {
    name: 'Defesa Especial (Bloqueio)',
    alias: '',
    attribute: 'poder',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
  },
  {
    name: 'Defesa Especial (Titânica)',
    alias: '',
    attribute: 'resistencia',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: true,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
  },
  {
    name: 'Inspirar (Buff de Cena)',
    alias: '',
    attribute: 'any',
    bonusType: 'flat',
    value: 2,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
  },
  {
    name: 'Plano de Ação (Agente)',
    alias: '',
    attribute: 'habilidade',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
  },
  {
    name: 'Frenesi de Combate (Bárbaro)',
    alias: '',
    attribute: 'poder',
    bonusType: 'attr_mod',
    value: 3,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
  },
  {
    name: 'Ajudante (Ganho)',
    alias: '',
    attribute: 'any',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 1,
    costValue: 2,
    costResource: 'PM',
  },
  {
    name: 'Carismático (Social)',
    alias: '',
    attribute: 'poder',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 0,
    costResource: 'none',
  },
  {
    name: 'Arena (+2 na sua Arena)',
    alias: '',
    attribute: 'any',
    bonusType: 'flat',
    value: 2,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 0,
    costResource: 'none',
  },
  {
    name: 'Inimigo (+2 contra Inimigo)',
    alias: '',
    attribute: 'any',
    bonusType: 'flat',
    value: 2,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 0,
    costResource: 'none',
  },
  {
    name: 'Ataque Múltiplo (1 Ataque Extra)',
    alias: '',
    attribute: 'poder',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
  },
  {
    name: 'Tiro Múltiplo (1 Alvo Extra)',
    alias: '',
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
  },
  {
    name: 'Uso de Perícia',
    alias: '',
    attribute: 'any',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 0,
    costResource: 'none',
  }
];
