import type { RollBonus } from '../../types/character';

export type TechniqueRequirement = {
  advantages?: string[];
  skills?: string[];
  anyOfAdvantages?: string[];
  anyOfSkills?: string[];
};

export type TechniqueCatalogEntry = Omit<RollBonus, 'id'> & {
  catalogId: string;
  description: string;
  universal?: boolean;
  requirements?: TechniqueRequirement;
};

export const TECHNIQUES_CATALOG: TechniqueCatalogEntry[] = [
  {
    catalogId: 'cancioneiro_popular',
    name: 'Cancioneiro Popular',
    alias: '',
    description: 'Canções emocionais e utilitárias; não pode ser usado em combate ou conflitos.',
    universal: false,
    requirements: { skills: ['arte'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'dobrar_elemento',
    name: 'Dobrar Elemento',
    alias: '',
    description: 'Controle elemental utilitário; não serve para causar dano direto.',
    universal: true,
    requirements: {},
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: -1,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'barreira_mistica',
    name: 'Barreira Mística',
    alias: '',
    description: 'Barreira defensiva mágica usada como reação, com modo base e aprimoramentos declarados em mesa.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'attr_mod',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'base',
    variants: [
      { id: 'base', label: 'Base', costValue: 1, costResource: 'PM', note: 'Usa Mística em vez de Luta na defesa.' },
      { id: 'aprimorada', label: 'Aprimorada', costValue: 2, costResource: 'PM', note: 'Escolha em mesa: Debilitante, Drenante, Elétrica, Espinhosa, Luminosa, Maciça ou Solidária.' }
    ]
  },
  {
    catalogId: 'raio_mistico',
    name: 'Raio Místico',
    alias: '',
    description: 'Ataque mágico direto com modo base e aprimoramentos declarados em mesa.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'attr_mod',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'base',
    variants: [
      { id: 'base', label: 'Base', costValue: 1, costResource: 'PM', note: 'Disparo padrão usando Mística em vez de Luta.' },
      { id: 'aprimorada', label: 'Aprimorada', costValue: 2, costResource: 'PM', note: 'Escolha em mesa: Ácido, Congelante, Debilitante, Distante, Elétrico ou Flamejante.' }
    ]
  },
  {
    catalogId: 'bola_de_fogo',
    name: 'Bola de Fogo',
    alias: '',
    description: 'Explosão mágica em área.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'flat',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'grimorio_debilitante',
    name: 'Grimório Debilitante',
    alias: '',
    description: 'Feitiço debilitante com efeitos escolhidos em mesa e duração/custo variáveis por modo.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'luz_trevas',
    variants: [
      { id: 'luz_trevas', label: 'Luz/Trevas', costValue: 3, costResource: 'PM', extraDice: -1, note: 'Ilumina ou escurece área Perto do alvo; efeitos visuais e duração duradoura declarados em mesa.' },
      { id: 'pes_de_chumbo', label: 'Pés de Chumbo', costValue: 3, costResource: 'PM', extraDice: -1, note: 'Aumenta a gravidade no alvo; ele pode resistir com Resistência contra sua Habilidade.' },
      { id: 'tempestade_mental', label: 'Tempestade Mental', costValue: 3, costResource: 'PM', extraDice: -1, note: 'Ataque que drena PM em vez de causar PV se superar a defesa.' },
      { id: 'terreno_escorregadio', label: 'Terreno Escorregadio de Neo', costValue: 3, costResource: 'PM', extraDice: -1, note: 'Área escorregadia causa Perda ligada a movimentação; pode gastar 9PM para tornar duradoura.' },
      { id: 'terreno_escorregadio_duradouro', label: 'Terreno Escorregadio Duradouro', costValue: 9, costResource: 'PM', extraDice: -1, note: 'Versão duradoura de Terreno Escorregadio de Neo.' }
    ]
  },
  {
    catalogId: 'metamagia',
    name: 'Metamagia',
    alias: '',
    description: 'Conjunto lendário para alterar o efeito de Magia e técnicas associadas.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 5,
    costResource: 'PM',
    xpCost: 20,
    xpCategory: 'legendary',
  },
  {
    catalogId: 'golpes',
    name: 'Golpes',
    alias: '',
    description: 'Conjunto de golpes de artes marciais; exige Luta e permite combos/manobras.',
    universal: false,
    requirements: { skills: ['luta'] },
    attribute: 'poder',
    bonusType: 'attr_mod',
    value: 1,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'grimorio_irritante',
    name: 'Grimório Irritante',
    alias: '',
    description: 'Magias irritantes e provocativas, com pouco efeito mecânico direto.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: -1,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'monasticismo_marcial',
    name: 'Monasticismo Marcial',
    alias: '',
    description: 'Treinamento marcial com opções de uso situacional escolhidas em jogo.',
    universal: false,
    requirements: {},
    attribute: 'resistencia',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'corpo_fechado',
    variants: [
      { id: 'corpo_fechado', label: 'Corpo Fechado', costValue: 2, costResource: 'PM', extraDice: 1, note: 'Ganho em um teste de Resistência para evitar um efeito negativo de vantagens ou técnicas.' },
      { id: 'inviolavel', label: 'Inviolável', costValue: 2, costResource: 'PM', extraDice: 1, note: 'Se mantiver imóvel, tem Ganho e defesa perfeita em todos os testes de defesa até seu próximo turno.' },
      { id: 'palma_de_ferro', label: 'Palma de Ferro', costValue: 2, costResource: 'PM', extraDice: 1, note: 'Ganho em um teste de Poder para quebrar objetos inanimados.' },
      { id: 'realinhar_chakras', label: 'Realinhar Chakras', costValue: 2, costResource: 'PM', note: 'Repete um teste de Resistência para eliminar efeito negativo.' },
      { id: 'realinhar_chakras_reforcado', label: 'Realinhar + Corpo Fechado', costValue: 4, costResource: 'PM', extraDice: 1, note: 'Repete o teste de Resistência e gasta +2PM para obter Corpo Fechado no mesmo teste.' }
    ]
  },
  {
    catalogId: 'ninjutsu',
    name: 'Ninjutsu',
    alias: '',
    description: 'Truques de infiltração e sabotagem com modos situacionais escolhidos em jogo.',
    universal: false,
    requirements: { skills: ['manha'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'bomba_de_fumaca',
    variants: [
      { id: 'bomba_de_fumaca', label: 'Bomba de Fumaça', costValue: 2, costResource: 'PM', extraDice: -1, note: 'Todos Perto ficam cegos por uma rodada, inclusive aliados.' },
      { id: 'corrida_ninja', label: 'Corrida Ninja', costValue: 2, costResource: 'PM', note: 'Dobra o deslocamento neste turno.' },
      { id: 'estrepes', label: 'Estrepes', costValue: 2, costResource: 'PM', extraDice: -1, note: 'Alvo Perto sofre Perda em um teste à sua escolha até seu próximo turno.' },
      { id: 'jutsu_de_troca', label: 'Jutsu de Troca', costValue: 2, costResource: 'PM', extraDice: 1, note: 'Como reação, troca de lugar com item próximo e recebe Ganho na defesa; apenas uma vez por rodada.' },
      { id: 'pipa_ninja', label: 'Pipa Ninja', costValue: 2, costResource: 'PM', note: 'Salta até Longe e voa por uma rodada; manutenção declarada em mesa.' }
    ]
  },
  {
    catalogId: 'pequenos_desejos',
    name: 'Pequenos Desejos',
    alias: '',
    description: 'Efeitos e ilusões inofensivas, distrativas e utilitárias.',
    universal: false,
    requirements: { skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'praga',
    name: 'Praga',
    alias: '',
    description: 'Roga uma praga contra o alvo, com efeito escolhido em mesa.',
    universal: false,
    requirements: { skills: ['mistica'] },
    attribute: 'poder',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'menos_um_atributo',
    variants: [
      { id: 'menos_um_atributo', label: '-1 em atributo', costValue: 2, costResource: 'PM', note: 'Se vencer Poder contra Resistência do alvo, ele sofre -1 em testes de um atributo até o fim da cena.' },
      { id: 'perda_em_teste', label: 'Perda em teste', costValue: 2, costResource: 'PM', extraDice: -1, note: 'Se vencer, o alvo sofre Perda em um único teste à sua escolha, até o fim da sessão.' },
      { id: 'custos_mais_caros', label: 'Custos +1PM', costValue: 2, costResource: 'PM', note: 'Se vencer, vantagens e técnicas do alvo custam +1PM até o fim da cena.' },
      { id: 'falha_critica_no_1', label: '1 vira falha crítica', costValue: 2, costResource: 'PM', note: 'Se vencer, qualquer resultado 1 do alvo causa falha crítica até o fim da cena.' }
    ]
  },
  {
    catalogId: 'super_movimento',
    name: 'Super-Movimento',
    alias: '',
    description: 'Movimentos impossíveis por treinamento ou magia, com modos situacionais escolhidos em jogo.',
    universal: false,
    requirements: { anyOfAdvantages: ['magia'], anyOfSkills: ['esporte', 'luta'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'andar_em_paredes',
    variants: [
      { id: 'andar_em_paredes', label: 'Andar em Paredes', costValue: 1, costResource: 'PM', note: 'Pode andar em paredes e tetos; para prender-se de novo após descer, gasta +1PM em mesa.' },
      { id: 'salto_extremo', label: 'Salto Extremo', costValue: 1, costResource: 'PM', note: 'Salta até Muito Longe com um movimento, sem Perda nem dano de queda ao voltar ao chão.' },
      { id: 'correr_sobre_agua', label: 'Correr sobre a Água', costValue: 1, costResource: 'PM', note: 'Correr sobre água ou superfície instável; em mesa requer 1PM por rodada para manter.' },
      { id: 'livre_de_contencao', label: 'Livre de Contenção', costValue: 1, costResource: 'PM', extraDice: 1, note: 'Ganho em um teste para se livrar de cordas, amarras e outras contenções.' }
    ]
  },
  {
    catalogId: 'absorver_mana',
    name: 'Absorver Mana',
    alias: '',
    description: 'Absorve mana do ambiente em vez de gastar energia própria.',
    universal: false,
    requirements: { skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 0,
    costResource: 'none',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'area_de_batalha',
    name: 'Área de Batalha',
    alias: '',
    description: 'Transporta combatentes para dimensão especial com vantagens escolhidas.',
    universal: false,
    requirements: { skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'combo',
    name: 'Combo',
    alias: '',
    description: 'Permite encadear golpes diferentes no mesmo turno.',
    universal: false,
    requirements: { skills: ['luta'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 1,
    costValue: 0,
    costResource: 'none',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'disparo_de_energia',
    name: 'Disparo de Energia',
    alias: '',
    description: 'Concentra energia espiritual e dispara contra alvo Longe, com níveis de carga situacionais.',
    universal: false,
    requirements: { anyOfAdvantages: ['magia'], anyOfSkills: ['luta'] },
    attribute: 'poder',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'padrao',
    variants: [
      { id: 'padrao', label: 'Padrão', costValue: 3, costResource: 'PM', value: 2, bonusType: 'attr_mod', note: 'Ataque Longe com Poder +2, sem Perda mesmo sem Alcance.' },
      { id: 'carga_1', label: 'Carga +1 mov.', costValue: 3, costResource: 'PM', value: 4, bonusType: 'attr_mod', note: 'Concentra 1 movimento para ganhar +2 Poder sem custo extra.' },
      { id: 'carga_2', label: 'Carga +2 mov.', costValue: 3, costResource: 'PM', value: 6, bonusType: 'attr_mod', note: 'Concentra 2 movimentos para ganhar +4 Poder total; respeite o limite real em mesa.' },
      { id: 'gritado', label: 'Nome Gritado', costValue: 2, costResource: 'PM', value: 2, bonusType: 'attr_mod', note: 'Se o jogador gritar o nome do disparo, o custo cai em 1PM.' }
    ]
  },
  {
    catalogId: 'consertar',
    name: 'Consertar',
    alias: '',
    description: 'Recupera PV de construtos com níveis variáveis de reparo.',
    universal: false,
    requirements: { skills: ['maquinas'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
    variantSelectionMode: 'cycle',
    selectedVariantId: '1d',
    variants: [
      { id: '1d', label: '1D PV', costValue: 2, costResource: 'PM', note: 'Gasta 2PM para curar 1D PV em um construto.' },
      { id: '2d', label: '2D PV', costValue: 4, costResource: 'PM', note: 'Gasta 4PM para curar 2D PV em um construto.' },
      { id: '3d', label: '3D PV', costValue: 6, costResource: 'PM', note: 'Gasta 6PM para curar 3D PV em um construto.' },
      { id: '4d', label: '4D PV', costValue: 8, costResource: 'PM', note: 'Gasta 8PM para curar 4D PV em um construto.' },
      { id: '5d', label: '5D PV', costValue: 10, costResource: 'PM', note: 'Gasta 10PM para curar 5D PV em um construto; respeite o limite real de Habilidade ou 5 em mesa.' }
    ]
  },
  {
    catalogId: 'encantar',
    name: 'Encantar',
    alias: '',
    description: 'Torna um alvo amigável, com uso mundano ou mágico reforçado.',
    universal: false,
    requirements: { anyOfAdvantages: ['magia'], anyOfSkills: ['arte', 'influencia'] },
    attribute: 'poder',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'padrao',
    variants: [
      { id: 'padrao', label: 'Padrão', costValue: 3, costResource: 'PM', note: 'Teste resistido de Poder contra Resistência; o alvo não pode agir agressivamente contra você.' },
      { id: 'magia_reforcada', label: 'Magia Reforçada', costValue: 4, costResource: 'PM', extraDice: 1, note: 'Usando Magia, pode gastar mais PM para obter bônus no teste; esta variante representa um reforço mínimo seguro.' }
    ]
  },
  {
    catalogId: 'invocar_elemental',
    name: 'Invocar Elemental',
    alias: '',
    description: 'Invoca criatura elemental que age como Ajudante.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 1,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'poeira_glacial',
    name: 'Poeira Glacial',
    alias: '',
    description: 'Ataque de frio que pode congelar o alvo.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: -1,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'relampago',
    name: 'Relâmpago',
    alias: '',
    description: 'Ataque elétrico que pode atordoar o alvo.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'setas_infaliveis_de_petrovna',
    name: 'Setas Infalíveis de Petrovna',
    alias: '',
    description: 'Cria setas mágicas que acertam automaticamente.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'flat',
    value: 1,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  }
];
