import type { RollBonus } from '../../types/character';

export type TechniqueRequirement = {
  advantages?: string[];
  skills?: string[];
  anyOfAdvantages?: string[];
  anyOfSkills?: string[];
};

export type TechniqueCatalogEntry = Omit<RollBonus, 'id'> & {
  catalogId: string;
  description: string;
  universal?: boolean;
  requirements?: TechniqueRequirement;
};

export const TECHNIQUES_CATALOG: TechniqueCatalogEntry[] = [
  {
    catalogId: 'cancioneiro_popular',
    name: 'Cancioneiro Popular',
    alias: '',
    description: 'Canções emocionais e utilitárias; não pode ser usado em combate ou conflitos.',
    universal: false,
    requirements: { skills: ['arte'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'dobrar_elemento',
    name: 'Dobrar Elemento',
    alias: '',
    description: 'Controle elemental utilitário; não serve para causar dano direto.',
    universal: true,
    requirements: {},
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: -1,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'barreira_mistica',
    name: 'Barreira Mística',
    alias: '',
    description: 'Barreira defensiva mágica usada como reação, com modo base e aprimoramentos declarados em mesa.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'attr_mod',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'base',
    variants: [
      { id: 'base', label: 'Base', costValue: 1, costResource: 'PM', note: 'Usa Mística em vez de Luta na defesa.' },
      { id: 'aprimorada', label: 'Aprimorada', costValue: 2, costResource: 'PM', note: 'Escolha em mesa: Debilitante, Drenante, Elétrica, Espinhosa, Luminosa, Maciça ou Solidária.' }
    ]
  },
  {
    catalogId: 'raio_mistico',
    name: 'Raio Místico',
    alias: '',
    description: 'Ataque mágico direto com modo base e aprimoramentos declarados em mesa.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'attr_mod',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
    variantSelectionMode: 'cycle',
    selectedVariantId: 'base',
    variants: [
      { id: 'base', label: 'Base', costValue: 1, costResource: 'PM', note: 'Disparo padrão usando Mística em vez de Luta.' },
      { id: 'aprimorada', label: 'Aprimorada', costValue: 2, costResource: 'PM', note: 'Escolha em mesa: Ácido, Congelante, Debilitante, Distante, Elétrico ou Flamejante.' }
    ]
  },
  {
    catalogId: 'bola_de_fogo',
    name: 'Bola de Fogo',
    alias: '',
    description: 'Explosão mágica em área.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'flat',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'grimorio_debilitante',
    name: 'Grimório Debilitante',
    alias: '',
    description: 'Feitiço que enfraquece capacidades do alvo.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: -1,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'metamagia',
    name: 'Metamagia',
    alias: '',
    description: 'Conjunto lendário para alterar o efeito de Magia e técnicas associadas.',
    universal: false,
    requirements: { advantages: ['magia'], skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 5,
    costResource: 'PM',
    xpCost: 20,
    xpCategory: 'legendary',
  },
  {
    catalogId: 'golpes',
    name: 'Golpes',
    alias: '',
    description: 'Conjunto de golpes de artes marciais; exige Luta e permite combos/manobras.',
    universal: false,
    requirements: { skills: ['luta'] },
    attribute: 'poder',
    bonusType: 'attr_mod',
    value: 1,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'grimorio_irritante',
    name: 'Grimório Irritante',
    alias: '',
    description: 'Magias irritantes e provocativas, com pouco efeito mecânico direto.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: -1,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'monasticismo_marcial',
    name: 'Monasticismo Marcial',
    alias: '',
    description: 'Treinamento marcial rigoroso com efeitos de foco e resistência.',
    universal: false,
    requirements: {},
    attribute: 'resistencia',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'ninjutsu',
    name: 'Ninjutsu',
    alias: '',
    description: 'Truques de infiltração e sabotagem.',
    universal: false,
    requirements: { skills: ['manha'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 1,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'pequenos_desejos',
    name: 'Pequenos Desejos',
    alias: '',
    description: 'Efeitos e ilusões inofensivas, distrativas e utilitárias.',
    universal: false,
    requirements: { skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'praga',
    name: 'Praga',
    alias: '',
    description: 'Roga uma praga contra o alvo, impondo penalidades diversas.',
    universal: false,
    requirements: { skills: ['mistica'] },
    attribute: 'poder',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: -1,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'super_movimento',
    name: 'Super-Movimento',
    alias: '',
    description: 'Movimentos impossíveis por treinamento ou magia.',
    universal: false,
    requirements: { anyOfAdvantages: ['magia'], anyOfSkills: ['esporte', 'luta'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 1,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'trick',
  },
  {
    catalogId: 'absorver_mana',
    name: 'Absorver Mana',
    alias: '',
    description: 'Absorve mana do ambiente em vez de gastar energia própria.',
    universal: false,
    requirements: { skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 0,
    costResource: 'none',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'area_de_batalha',
    name: 'Área de Batalha',
    alias: '',
    description: 'Transporta combatentes para dimensão especial com vantagens escolhidas.',
    universal: false,
    requirements: { skills: ['mistica'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'combo',
    name: 'Combo',
    alias: '',
    description: 'Permite encadear golpes diferentes no mesmo turno.',
    universal: false,
    requirements: { skills: ['luta'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 1,
    costValue: 0,
    costResource: 'none',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'disparo_de_energia',
    name: 'Disparo de Energia',
    alias: '',
    description: 'Concentra energia espiritual e dispara contra alvo Longe.',
    universal: false,
    requirements: { anyOfAdvantages: ['magia'], anyOfSkills: ['luta'] },
    attribute: 'poder',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'consertar',
    name: 'Consertar',
    alias: '',
    description: 'Recupera PV de construtos.',
    universal: false,
    requirements: { skills: ['maquinas'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 2,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'encantar',
    name: 'Encantar',
    alias: '',
    description: 'Torna um alvo extremamente amigável a você.',
    universal: false,
    requirements: { anyOfAdvantages: ['magia'], anyOfSkills: ['arte', 'influencia'] },
    attribute: 'poder',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 1,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'invocar_elemental',
    name: 'Invocar Elemental',
    alias: '',
    description: 'Invoca criatura elemental que age como Ajudante.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'none',
    value: 0,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 1,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'poeira_glacial',
    name: 'Poeira Glacial',
    alias: '',
    description: 'Ataque de frio que pode congelar o alvo.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: -1,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'relampago',
    name: 'Relâmpago',
    alias: '',
    description: 'Ataque elétrico que pode atordoar o alvo.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'attr_mod',
    value: 2,
    duration: 'instant',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 3,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  },
  {
    catalogId: 'setas_infaliveis_de_petrovna',
    name: 'Setas Infalíveis de Petrovna',
    alias: '',
    description: 'Cria setas mágicas que acertam automaticamente.',
    universal: false,
    requirements: { advantages: ['magia'] },
    attribute: 'habilidade',
    bonusType: 'flat',
    value: 1,
    duration: 'scene',
    critThresholdMod: 0,
    autoCrit: false,
    extraDice: 0,
    costValue: 1,
    costResource: 'PM',
    xpCost: 10,
    xpCategory: 'common',
  }
];
