export const ADVANTAGE_VARIANT_OPTIONS: Record<string, Array<{ key: string; label: string; cost?: string }>> = {
  ataque_especial: [
    { key: 'potente', label: 'Potente (P+2)' },
    { key: 'potente_ii', label: 'Potente II (P+4)' },
    { key: 'perigoso', label: 'Perigoso (Crítico 5+)' },
    { key: 'preciso', label: 'Preciso (Usa H no ataque)' },
    { key: 'choque', label: 'Choque (Usa R no ataque)' },
    { key: 'area', label: 'Área (Afeta todos Perto)' },
    { key: 'distante', label: 'Distante (Ataque Longe)' },
    { key: 'amplo', label: 'Amplo (Múltiplos alvos)' },
    { key: 'penetrante', label: 'Penetrante (Perda na Defesa)' },
    { key: 'titanico', label: 'Titânico (Crítico Automático)' },
  ],
  defesa_especial: [
    { key: 'tenaz', label: 'Tenaz (R+2)' },
    { key: 'tenaz_ii', label: 'Tenaz II (R+4)' },
    { key: 'blindada', label: 'Blindada (Crítico 5+)' },
    { key: 'esquiva', label: 'Esquiva (Usa H na defesa)' },
    { key: 'bloqueio', label: 'Bloqueio (Usa P na defesa)' },
    { key: 'cobertura', label: 'Cobertura (Protege aliado Perto)' },
    { key: 'reflexao', label: 'Reflexão (Devolve ataque em crítico)' },
    { key: 'titanica', label: 'Titânica (Crítico Automático)' },
  ],
  alcance: [
    { key: 'perto', label: 'Alcance 1 (Até Perto)', cost: '1pt' },
    { key: 'longe', label: 'Alcance 2 (Até Longe)', cost: '2pt' },
  ],
  imune: [
    { key: 'anfibio', label: 'Anfíbio (Respiração Aquática)' },
    { key: 'resiliente', label: 'Resiliente (Venenos e Doenças)' },
    { key: 'sem_mente', label: 'Sem Mente (Imunidade Mental)' },
    { key: 'sem_vida', label: 'Sem Vida (Sem Necessidades Vitais)' },
    { key: 'abiotico', label: 'Abiótico (Fome, Sede e Ar)' },
    { key: 'sono', label: 'Sem Sono (Não Precisa Dormir)' },
  ],
  sentido: [
    { key: 'infravisao', label: 'Infravisão' },
    { key: 'radar', label: 'Radar' },
    { key: 'raio_x', label: 'Raio X' },
    { key: 'agucado', label: 'Sentido Aguçado' },
    { key: 'ver_o_invisivel', label: 'Ver o Invisível' },
  ],
  ajudante: [
    { key: 'combatente', label: 'Combatente' },
    { key: 'defensor', label: 'Defensor' },
    { key: 'curandeiro', label: 'Curandeiro' },
    { key: 'especialista', label: 'Especialista' },
    { key: 'conjurador', label: 'Conjurador' },
  ],
  arena: [
    { key: 'agua', label: 'Água / Aquático' },
    { key: 'ceu', label: 'Céu / Aéreo' },
    { key: 'ermos', label: 'Ermos / Floresta' },
    { key: 'subterraneo', label: 'Subterrâneo' },
    { key: 'urbano', label: 'Urbano' },
    { key: 'espaco', label: 'Espaço / Outro Plano' },
  ],
  inimigo: [
    { key: 'comum', label: 'Inimigo comum', cost: '1pt' },
    { key: 'maior', label: 'Inimigo maior', cost: '2pt' },
  ],
  inventario: [
    { key: 'nivel_1', label: 'Nível 1', cost: '1pt' },
    { key: 'nivel_2', label: 'Nível 2', cost: '2pt' },
    { key: 'nivel_3', label: 'Nível 3', cost: '3pt' },
  ],
  maestria: [
    { key: 'animais', label: 'Animais' },
    { key: 'arte', label: 'Arte' },
    { key: 'esporte', label: 'Esporte' },
    { key: 'influencia', label: 'Influência' },
    { key: 'luta', label: 'Luta' },
    { key: 'manha', label: 'Manha' },
    { key: 'maquinas', label: 'Máquinas' },
    { key: 'medicina', label: 'Medicina' },
    { key: 'mistica', label: 'Mística' },
    { key: 'percepcao', label: 'Percepção' },
    { key: 'saber', label: 'Saber' },
    { key: 'sobrevivencia', label: 'Sobrevivência' },
  ],
  mentor: [
    { key: 'animais', label: 'Animais' },
    { key: 'arte', label: 'Arte' },
    { key: 'esporte', label: 'Esporte' },
    { key: 'influencia', label: 'Influência' },
    { key: 'luta', label: 'Luta' },
    { key: 'manha', label: 'Manha' },
    { key: 'maquinas', label: 'Máquinas' },
    { key: 'medicina', label: 'Medicina' },
    { key: 'mistica', label: 'Mística' },
    { key: 'percepcao', label: 'Percepção' },
    { key: 'saber', label: 'Saber' },
    { key: 'sobrevivencia', label: 'Sobrevivência' },
  ],
  instrutor: [
    { key: 'animais', label: 'Animais' },
    { key: 'arte', label: 'Arte' },
    { key: 'esporte', label: 'Esporte' },
    { key: 'influencia', label: 'Influência' },
    { key: 'luta', label: 'Luta' },
    { key: 'manha', label: 'Manha' },
    { key: 'maquinas', label: 'Máquinas' },
    { key: 'medicina', label: 'Medicina' },
    { key: 'mistica', label: 'Mística' },
    { key: 'percepcao', label: 'Percepção' },
    { key: 'saber', label: 'Saber' },
    { key: 'sobrevivencia', label: 'Sobrevivência' },
  ],
  punicao: [
    { key: 'leve', label: 'Leve', cost: '1pt' },
    { key: 'grave', label: 'Grave', cost: '2pt' },
  ],
  transformacao: [
    { key: 'forma_menor', label: 'Forma menor', cost: '1pt' },
    { key: 'forma_maior', label: 'Forma maior', cost: '2pt' },
  ],
  artefato: [
    { key: 'simples', label: 'Artefato simples', cost: '1pt' },
    { key: 'maior', label: 'Artefato maior', cost: '2pt' },
    { key: 'lendario', label: 'Artefato lendário', cost: '3pt' },
  ],
  grimorio: [
    { key: 'basico', label: 'Grimório básico', cost: '1pt' },
    { key: 'avancado', label: 'Grimório avançado', cost: '2pt' },
    { key: 'supremo', label: 'Grimório supremo', cost: '3pt' },
  ],
  invisivel: [
    { key: 'parcial', label: 'Invisibilidade parcial', cost: '1pt' },
    { key: 'total', label: 'Invisibilidade total', cost: '2pt' },
  ],
  regeneracao: [
    { key: 'leve', label: 'Regeneração leve (1 PV/rodada)', cost: '1pt' },
    { key: 'forte', label: 'Regeneração forte (2 PV/rodada)', cost: '2pt' },
  ],
  riqueza: [
    { key: 'rica', label: 'Riqueza', cost: '2pt' },
    { key: 'muito_rica', label: 'Muita riqueza', cost: '4pt' },
    { key: 'milionaria', label: 'Riqueza milionária', cost: '6pt' },
  ],
};

export const DISADVANTAGE_VARIANT_OPTIONS: Record<string, Array<{ key: string; label: string; cost?: string }>> = {
  ambiente: [
    { key: 'agua', label: 'Água / Aquático', cost: '-1pt' },
    { key: 'ceu', label: 'Céu / Aéreo', cost: '-1pt' },
    { key: 'ermos', label: 'Ermos / Floresta', cost: '-1pt' },
    { key: 'subterraneo', label: 'Subterrâneo', cost: '-1pt' },
    { key: 'urbano', label: 'Urbano', cost: '-1pt' },
    { key: 'espaco', label: 'Espaço / Outro Plano', cost: '-1pt' },
  ],
  inapto: [
    { key: 'animais', label: 'Animais', cost: '-1pt' },
    { key: 'arte', label: 'Arte', cost: '-1pt' },
    { key: 'esporte', label: 'Esporte', cost: '-1pt' },
    { key: 'influencia', label: 'Influência', cost: '-1pt' },
    { key: 'luta', label: 'Luta', cost: '-1pt' },
    { key: 'manha', label: 'Manha', cost: '-1pt' },
    { key: 'maquinas', label: 'Máquinas', cost: '-1pt' },
    { key: 'medicina', label: 'Medicina', cost: '-1pt' },
    { key: 'mistica', label: 'Mística', cost: '-1pt' },
    { key: 'percepcao', label: 'Percepção', cost: '-1pt' },
    { key: 'saber', label: 'Saber', cost: '-1pt' },
    { key: 'sobrevivencia', label: 'Sobrevivência', cost: '-1pt' },
  ],
  protegido: [
    { key: 'comum', label: 'Protegido comum', cost: '-1pt' },
    { key: 'indefeso', label: 'Protegido indefeso', cost: '-2pt' },
  ],
  utensilio: [
    { key: 'comum', label: 'Utensílio comum', cost: '-1pt' },
    { key: 'vital', label: 'Utensílio vital', cost: '-2pt' },
  ],
  restricao: [
    { key: 'leve', label: 'Restrição leve', cost: '-1pt' },
    { key: 'grave', label: 'Restrição grave', cost: '-2pt' },
  ],
  fraqueza: [
    { key: 'leve', label: 'Fraqueza leve (Incomum)', cost: '-1pt' },
    { key: 'grave', label: 'Fraqueza grave (Comum)', cost: '-2pt' },
  ],
  aura: [
    { key: 'leve', label: 'Aura leve', cost: '-1pt' },
    { key: 'grave', label: 'Aura grave', cost: '-2pt' },
  ],
  assombrado: [
    { key: 'leve', label: 'Assombrado leve', cost: '-1pt' },
    { key: 'grave', label: 'Assombrado grave', cost: '-2pt' },
  ],
  maldicao: [
    { key: 'leve', label: 'Maldição leve', cost: '-1pt' },
    { key: 'grave', label: 'Maldição grave', cost: '-2pt' },
  ],
  pacifista: [
    { key: 'parcial', label: 'Pacifista parcial', cost: '-1pt' },
    { key: 'total', label: 'Pacifista total', cost: '-2pt' },
  ],
  codigo: [
    { key: 'honra', label: 'Código de Honra', cost: '-1pt' },
    { key: 'heroico', label: 'Código Heroico', cost: '-1pt' },
    { key: 'cavalheirismo', label: 'Código de Cavalheirismo', cost: '-1pt' },
    { key: 'justica', label: 'Código de Justiça', cost: '-1pt' },
    { key: 'pacifismo', label: 'Código de Pacifismo', cost: '-1pt' },
    { key: 'lealdade', label: 'Código de Lealdade', cost: '-1pt' },
    { key: 'dahllan', label: 'Código Dahllan', cost: '-1pt' },
    { key: 'dragoes', label: 'Código dos Dragões', cost: '-1pt' },
    { key: 'gratidao', label: 'Código da Gratidão', cost: '-1pt' },
    { key: 'cacador', label: 'Código do Caçador', cost: '-1pt' },
    { key: 'combate', label: 'Código de Combate', cost: '-1pt' },
    { key: 'derrota', label: 'Código da Derrota', cost: '-1pt' },
    { key: 'redencao', label: 'Código da Redenção', cost: '-1pt' },
  ],
  transtorno: [
    { key: 'fobia', label: 'Fobia', cost: '-1pt' },
    { key: 'mitomania', label: 'Mitomania', cost: '-1pt' },
    { key: 'compulsao', label: 'Compulsão', cost: '-1pt' },
    { key: 'cleptomania', label: 'Cleptomania', cost: '-1pt' },
    { key: 'distracao', label: 'Distração', cost: '-1pt' },
    { key: 'fantasia', label: 'Fantasia', cost: '-1pt' },
    { key: 'timidez', label: 'Timidez', cost: '-1pt' },
  ],
};
